theme: jekyll-theme-hacker
title: Nick Santini's GitHub
description: Nick Santini's GitHub contains computer science projects that are both complete and works in progress.
google_analytics: UA-145053065-1
